### ISSUE TITLE
false info regarding node requirement

### ISSUE THREAD

**Issue by DodoGames7** [Munz1211-Project/DISCORD-JS-V14-TEMPLATE#25]
first of all djs v14 changed the node.js requirement from 16.6 to 16.9 but here the project of the readme file says that you should have node.js v16 (at least 16.6 or newer) when this is false, this could put someone else being confused on why the template is not working for them just because their node version is lower, i kindly ask you to fix that if possible

**Comment by Munz1211** [comment]
Done
